### ISSUE TITLE
LoadError: cannot load such file -- 

### ISSUE THREAD

**Issue by s0kil** [microverseinc/linters-config#94] opened 2020-08-20 15:15 UTC
RSpec fails multiple times in CI due to this error.

```
An error occurred while loading ./spec/helpers/git_spec.rb. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'git'

LoadError:
  cannot load such file -- git
# ./lib/helpers/git.rb:1:in `<top (required)>'
# ./spec/helpers/git_spec.rb:3:in `require_relative'
# ./spec/helpers/git_spec.rb:3:in `<top (required)>'

Finished in 0.00003 seconds (files took 0.12259 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

##[error]Process completed with exit code 1.
```

To resolve this error, run `rspec` inside the project context `bundle exec rspec`

**Comment by shshamim63** [comment] 2020-09-02 12:51
Hi @s0kil :wave: Thanks for opening the issue, well I tried to regenerate the issue you mentioned, but was not able to do so. So I will keep the issue and the [merge request](https://github.com/microverseinc/linters-config/pull/95) open.

**Comment by bolah2009** [comment] 2020-09-25 16:56
We can close it since it's not reproducible, we can re-open when a similar issue occurs.

**Comment by uryelah** [comment] 2020-10-09 20:38
The issue was mentioned again on Slack at [this thread](https://microverse-students.slack.com/archives/GA812K2TC/p1602274801168200).
@shshamim63 Check the thread linked again. It seems the issue might have to do with the `rest-client` gem.

**Comment by kcotrinam** [comment] 2020-10-09 20:48
RSpec fails and throws the following error
`An error occurred while loading ./spec/request_joke_spec.rb - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'rest-client'

LoadError:
  cannot load such file -- rest-client
# ./lib/request_joke.rb:2:in `<top (required)>'
# ./spec/request_joke_spec.rb:1:in `require_relative'
# ./spec/request_joke_spec.rb:1:in `<top (required)>'

Finished in 0.00003 seconds (files took 0.21811 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

##[error]Process completed with exit code 1.`
To resolve this error I had to add `run: bundle exec rspec` to the tests.yml file

**Comment by s0kil** [comment] 2020-10-09 20:51
Here are the before and after commits where I've experienced this issue:
B: https://github.com/danielsokil/GITS/runs/1008309660
A: https://github.com/danielsokil/GITS/runs/1008334280

**Comment by uryelah** [comment] 2020-10-09 21:14
I managed to reproduce the issue here:
https://github.com/uryelah/reproduce-rspect-gitaction-error/pull/1/checks?check_run_id=1233455785

1. It takes creating a ruby project that uses a Gem file requiring `gem 'rest-client', '~> 2.1'`.

2. Then, creating at least one method/class that requires the `rest-client` gem.

3. Create a spec folder with a spec_helper file and a test file to test the method/class created above.

4. Committing and pushing the code should result in the Rspec `Failure/Error: require 'rest-client'` error.

**Comment by shshamim63** [comment] 2020-10-12 08:04
Thanks for the heads up @uryelah . 
@s0kil and @kcotrinam thanks for bringing the issue. This is happening because while testing a class you need to access the gem. Requiring it in the actual file does not make it accessible in the spec files. That is why the Rspec is rendering the error. I will generate an update as soon as possible.

**Comment by s0kil** [comment] 2020-10-12 12:43
@shshamim63 If I understand you correctly, we should be able to add `require 'bundler/setup'` into the `spec_helper.rb` file, and that will resolve this issue.

**Comment by shshamim63** [comment] 2020-10-12 12:46
@s0kil Yes, you got it correctly. For example the issue with the @kcotrinam project, I resolved it with the following format.
https://github.com/shshamim63/testing-liner-bot/blob/0042f48badaab699cd212aa9312b4fdaf0341ea0/spec/spec_helper.rb#L1-L4

**Comment by shshamim63** [comment] 2020-10-15 05:50
As this issue is not related to the linter configuration I am closing it.

**Closed by shshamim63** 2020-10-15 05:50 UTC
